### ISSUE TITLE
Fails to build with OpenSSL 1.1

### ISSUE THREAD

**Issue by rhertzog** [moxie0/sslsniff#27]
Hello,

if you try to build sslsniff with OpenSSL 1.1 it will fail:
```
In file included from SSLBridge.hpp:41:0,
                 from HTTPSBridge.hpp:24,
                 from FirefoxUpdater.hpp:23,
                 from FirefoxAddonUpdater.hpp:26,
                 from SSLConnectionManager.cpp:20:
certificate/Certificate.hpp: In member function 'void Certificate::parseCommonName(X509*)':
certificate/Certificate.hpp:95:39: error: invalid use of incomplete type 'X509 {aka struct x509_st}'
     std::string distinguishedName(cert->name);
                                       ^~
```

Basically OpenSSL made many structures opaque and you have to use various API calls to access the underlying data.

On https://wiki.openssl.org/index.php/1.1_API_Changes you can see some of the changes. There are also updated man pages at https://www.openssl.org/docs/manmaster/ that should contain useful information.

This was initially filed in Debian here: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=828557
